//! rrt-docs: the reference docs under `docs/`, kept honest.
//!
//! ```text
//! cargo run -q -p rrt-docs -- index    # regenerate docs/README.md
//! cargo run -q -p rrt-docs -- check    # every check below; non-zero exit on a problem
//! ```
//!
//! `docs/README.md` is generated from the front matter of every page, so the
//! index cannot drift from the pages. `check` also holds the pages to the
//! code: every crate under `crates/` has a page in `docs/crates/`, every item
//! a page's `covers` names (`rrt_input::Input::read`) is still declared in
//! that crate's source, every crate opens with a `//!` header and takes the
//! workspace lints. The rules are the `docs` skill's
//! (`.claude/skills/docs/SKILL.md`).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// The honesty knob, as the skill defines it.
const STATUS: [&str; 3] = ["solid", "partial", "draft"];

/// The folders under `docs/`: name, heading, what belongs there.
const SECTIONS: [(&str, &str, &str); 3] = [
    ("crates", "Crates", "One page per crate: what it is for, its entry points, what it does not do."),
    (
        "conventions",
        "Conventions",
        "Rules every crate and every game on retro_rt shares: bit orders, units, colour, timing.",
    ),
    ("guides", "Guides", "How to do one thing with the runtime, start to finish."),
];

const HEADER: &str = "# retro_rt reference

What is true about retro_rt, the shared runtime for the Rust ports of retro
games: the crates, the conventions they share, and how to build a game on
them. Generated by `cargo run -q -p rrt-docs -- index` - edit the pages, not
this file.

Read this first, then the page for the crate you are touching. `status` is the
honesty knob: `solid` means every public item the page covers is documented,
tested and described here as it behaves; `partial` means named gaps remain;
`draft` means written ahead of verification. `covers` names the items a page
describes, and `rrt-docs check` fails when one of them no longer exists.
";

/// `key: value` lines between the opening `---` and the next.
fn front_matter(text: &str) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let Some(body) = text.strip_prefix("---\n") else { return out };
    let Some(end) = body.find("\n---\n") else { return out };
    for line in body[..end].lines() {
        if let Some((key, value)) = line.split_once(':') {
            out.insert(key.trim().to_string(), value.trim().to_string());
        }
    }
    out
}

/// The `.md` pages in a section, sorted, with their front matter.
fn pages(docs: &Path, section: &str) -> Vec<(PathBuf, BTreeMap<String, String>)> {
    let mut found: Vec<PathBuf> = std::fs::read_dir(docs.join(section))
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "md"))
        .collect();
    found.sort();
    found
        .into_iter()
        .map(|p| {
            let text = std::fs::read_to_string(&p).unwrap_or_default();
            let meta = front_matter(&text);
            (p, meta)
        })
        .collect()
}

/// A crate under `crates/`: its directory name and Cargo description.
struct Crate {
    name: String,
    dir: PathBuf,
    description: String,
    manifest: String,
}

fn crates(root: &Path) -> Vec<Crate> {
    let mut out: Vec<Crate> = std::fs::read_dir(root.join("crates"))
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.join("Cargo.toml").exists())
        .map(|dir| {
            let manifest = std::fs::read_to_string(dir.join("Cargo.toml")).unwrap_or_default();
            let description = manifest
                .lines()
                .find_map(|l| l.strip_prefix("description = "))
                .map(|v| v.trim().trim_matches('"').to_string())
                .unwrap_or_default();
            let name = dir.file_name().unwrap().to_string_lossy().to_string();
            Crate { name, dir, description, manifest }
        })
        .collect();
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out
}

fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn render_index(root: &Path) -> String {
    let docs = root.join("docs");
    let mut out = String::from(HEADER);
    out.push_str(
        "\n## Crates at a glance\n\nFrom each crate's `Cargo.toml`.\n\n| Crate | What it is |\n| --- | --- |\n",
    );
    for c in crates(root) {
        let page = docs.join("crates").join(format!("{}.md", c.name));
        let name = if page.exists() { format!("[{0}](crates/{0}.md)", c.name) } else { c.name.clone() };
        out.push_str(&format!("| {name} | {} |\n", cell(&c.description)));
    }
    for (section, heading, blurb) in SECTIONS {
        let found = pages(&docs, section);
        if found.is_empty() {
            continue;
        }
        out.push_str(&format!("\n## {heading}\n\n{blurb}\n"));
        out.push_str("\n| Page | Status | Crates | Covers |\n| --- | --- | --- | --- |\n");
        for (path, meta) in found {
            let name = path.file_name().unwrap().to_string_lossy();
            let stem = path.file_stem().unwrap().to_string_lossy();
            let get = |k: &str, d: &str| meta.get(k).cloned().unwrap_or_else(|| d.to_string());
            out.push_str(&format!(
                "| [{}]({section}/{name}) | {} | {} | {} |\n",
                cell(&get("title", &stem)),
                get("status", "?"),
                cell(&get("crates", "?")),
                cell(&get("covers", "")),
            ));
        }
    }
    out
}

/// Relative `.md` link targets in a page: `](foo.md)`, `](../x/foo.md#a)`.
fn md_links(text: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut rest = text;
    while let Some(at) = rest.find("](") {
        rest = &rest[at + 2..];
        let end = rest.find(')').unwrap_or(rest.len());
        let target = rest[..end].split('#').next().unwrap_or("");
        if target.ends_with(".md") && !target.contains(':') {
            out.push(target);
        }
    }
    out
}

/// Every `.rs` file under `dir`, read.
fn sources(dir: &Path) -> Vec<String> {
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(dir) else { return out };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            out.extend(sources(&p));
        } else if p.extension().is_some_and(|x| x == "rs") {
            out.push(std::fs::read_to_string(&p).unwrap_or_default());
        }
    }
    out
}

/// Whether `name` is declared in `src`: as a fn, type, const, module,
/// field-less variant line, or a `pub use` re-export.
fn declares(src: &[String], name: &str) -> bool {
    let kinds = ["fn ", "struct ", "enum ", "trait ", "const ", "static ", "mod ", "type ", "macro_rules! "];
    src.iter().any(|text| {
        text.lines().any(|line| {
            let l = line.trim_start();
            let l = l.strip_prefix("pub(crate) ").or_else(|| l.strip_prefix("pub ")).unwrap_or(l);
            // `const fn`, `unsafe fn`, `async fn` declare a fn.
            let l = ["const ", "unsafe ", "async "]
                .iter()
                .find_map(|q| l.strip_prefix(q).filter(|r| r.starts_with("fn ")))
                .unwrap_or(l);
            let declared = kinds.iter().any(|k| {
                l.strip_prefix(k).is_some_and(|r| {
                    r.strip_prefix(name)
                        .is_some_and(|after| !after.starts_with(|c: char| c.is_alphanumeric() || c == '_'))
                })
            });
            // An enum variant or a struct field: `Name,` `Name(` `Name {` `name:`.
            let member = l
                .strip_prefix(name)
                .is_some_and(|after| after.starts_with([',', '(', ' ', ':', '{']) && line.starts_with("    "));
            let reexport = l.starts_with("use ") && l.contains(name);
            declared || member || reexport
        })
    })
}

fn check(root: &Path) -> Vec<String> {
    let docs = root.join("docs");
    let all = crates(root);
    let by_lib: BTreeMap<String, &Crate> = all.iter().map(|c| (c.name.replace('-', "_"), c)).collect();
    let mut problems = Vec::new();
    for entry in std::fs::read_dir(&docs).into_iter().flatten().flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if entry.path().is_dir() && !SECTIONS.iter().any(|(s, _, _)| *s == name) {
            problems.push(format!(
                "docs/{name}/ is not a section in crates/rrt-docs/src/main.rs - its pages never reach the index"
            ));
        }
    }
    for c in &all {
        let page = format!("docs/crates/{}.md", c.name);
        if !root.join(&page).exists() {
            problems.push(format!("crates/{} has no page: write {page}", c.name));
        }
        if c.description.is_empty() {
            problems.push(format!("crates/{}/Cargo.toml has no description", c.name));
        }
        if !c.manifest.contains("[lints]\nworkspace = true") {
            problems.push(format!("crates/{}/Cargo.toml does not take the workspace lints", c.name));
        }
        let head = ["src/lib.rs", "src/main.rs"].iter().find_map(|f| std::fs::read_to_string(c.dir.join(f)).ok());
        if !head.is_some_and(|t| t.starts_with("//!")) {
            problems.push(format!("crates/{} does not open with a //! header", c.name));
        }
    }
    let mut sources_of: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (section, _, _) in SECTIONS {
        for (path, meta) in pages(&docs, section) {
            let at = path.strip_prefix(root).unwrap_or(&path).display().to_string();
            for wanted in ["title", "status", "crates", "covers"] {
                if meta.get(wanted).is_none_or(|v| v.is_empty()) {
                    problems.push(format!("{at} has no {wanted}"));
                }
            }
            if let Some(status) = meta.get("status").filter(|s| !s.is_empty())
                && !STATUS.contains(&status.as_str())
            {
                problems.push(format!("{at}: unknown status {status:?}; one of {}", STATUS.join(", ")));
            }
            for name in meta.get("crates").map(String::as_str).unwrap_or("").split(',').map(str::trim) {
                if !name.is_empty() && name != "all" && !all.iter().any(|c| c.name == name) {
                    problems.push(format!("{at}: no crate {name:?} under crates/"));
                }
            }
            for item in meta.get("covers").map(String::as_str).unwrap_or("").split(',').map(str::trim) {
                let Some((lib, _)) = item.split_once("::") else { continue };
                let Some(c) = by_lib.get(lib) else {
                    problems.push(format!("{at}: covers {item}, but there is no crate {lib}"));
                    continue;
                };
                let src = sources_of.entry(lib.to_string()).or_insert_with(|| sources(&c.dir.join("src")));
                let last = item.rsplit("::").next().unwrap_or(item);
                if !declares(src, last) {
                    problems.push(format!("{at}: covers {item}, which crates/{}/src does not declare", c.name));
                }
            }
            let text = std::fs::read_to_string(&path).unwrap_or_default();
            for target in md_links(&text) {
                if !path.parent().unwrap().join(target).exists() {
                    problems.push(format!("{at}: dead link to {target}"));
                }
            }
        }
    }
    if std::fs::read_to_string(docs.join("README.md")).ok().as_deref() != Some(render_index(root).as_str()) {
        problems.push("docs/README.md is stale - run `cargo run -q -p rrt-docs -- index`".into());
    }
    problems
}

/// The workspace root: the nearest directory up from here with `crates/`
/// and `docs/`.
fn root() -> PathBuf {
    let mut at = std::env::current_dir().expect("current directory");
    loop {
        if at.join("crates").is_dir() && at.join("docs").is_dir() {
            return at;
        }
        if !at.pop() {
            return PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        }
    }
}

fn main() {
    let root = root();
    match std::env::args().nth(1).as_deref() {
        Some("index") => {
            let text = render_index(&root);
            if let Err(e) = std::fs::write(root.join("docs/README.md"), text) {
                eprintln!("docs/README.md: {e}");
                std::process::exit(1);
            }
            let total: usize = SECTIONS.iter().map(|(s, _, _)| pages(&root.join("docs"), s).len()).sum();
            println!("{total} pages -> docs/README.md");
        }
        Some("check") => {
            let problems = check(&root);
            for p in &problems {
                eprintln!("{p}");
            }
            if !problems.is_empty() {
                eprintln!("{} problems", problems.len());
                std::process::exit(1);
            }
            println!("docs ok");
        }
        _ => {
            eprintln!("usage: rrt-docs index|check");
            std::process::exit(2);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn front_matter_reads_key_values() {
        let m = front_matter("---\ntitle: A: b\nstatus: solid\n---\n# A\n");
        assert_eq!(m.get("title").map(String::as_str), Some("A: b"));
        assert_eq!(m.get("status").map(String::as_str), Some("solid"));
    }

    #[test]
    fn declarations_are_found_by_their_last_segment() {
        let src = vec!["pub const fn libpad(self) -> u16 {}\npub struct Input {\n    pub shape: StickShape,\n}\nimpl Input {\n    pub fn read(&mut self) {}\n}\npub enum E {\n    Raw,\n}\n".to_string()];
        assert!(declares(&src, "Input"));
        assert!(declares(&src, "read"));
        assert!(declares(&src, "shape"));
        assert!(declares(&src, "Raw"));
        assert!(declares(&src, "libpad"), "a const fn is a fn");
        assert!(!declares(&src, "rea"));
        assert!(!declares(&src, "Missing"));
    }
}
